vortexa:
  bot-instance:
    botKey: 'klok_test'
    className: 'cn.com.vortexa.script_bot.daily.klok.KlokBot'
    classFileName: 'KlokBot.java'
    accountConfig:
      configFilePath: "/Users/helei/develop/ideaworkspace/BotFramework/botData/config/app/klok_google.xlsx"
    customConfig:
      two_captcha_api_key:
