vortexa:
  bot-instance:
    botKey: 'monadscore_test'
    className: 'cn.com.vortexa.script_bot.daily.monadscore.MonadScoreBot'
    accountConfig:
      configFilePath: "/Users/helei/develop/ideaworkspace/BotFramework/botData/config/app/monad_score_google.xlsx"
    customConfig:
      invite_code: ''
