vortexa:
  bot-instance:
    botKey: 'haha_wallet_test'
    className: 'cn.com.vortexa.script_bot.daily.haha_wallet.HaHaWalletBot'
    classFileName: 'HaHaWalletBot.java'
    extraClass:
      - className: "cn.com.vortexa.script_bot.daily.haha_wallet.HahaWalletSelenium"
        classFileName: "HahaWalletSelenium.java"
    accountConfig:
      configFilePath: "/Users/helei/develop/ideaworkspace/BotFramework/botData/config/app/haha_wallet_google.xlsx"
    customConfig:
      invite_code: ''
