vortexa:
  bot-instance:
    botKey: 'flow3_bot_test'
    className: 'cn.com.vortexa.script_bot.depin.flow3.Flow3Bot'
    accountConfig:
      configFilePath: "app_resource_config:flow3_google.xlsx"
    customConfig:
      invite_code: "ou3n2sUVD"
      two_captcha_api_key: ""
